name: Build Code Server Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Prepare Claude Extension
        run: |
          # 检查claude.vsix是否存在，如果不存在则创建一个空文件
          if [ ! -f "claude.vsix" ]; then
            echo "WARNING: claude.vsix not found. Creating a placeholder."
            echo "Please replace this with the actual extension file." > claude.vsix
          fi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/yjq001/code-server:latest
