name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit SHA to checkout'
        required: true
        default: 'main'
      version:
        description: 'Version tag for the Docker image'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  SOURCE_REPO: yjq001/money-backend
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPO }}
          ref: ${{ github.event.inputs.ref || 'main' }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Verify checkout
        run: |
          echo "Checking out from ${{ env.SOURCE_REPO }}"
          echo "Current directory contents:"
          ls -la
          echo "Dockerfile contents:"
          cat Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.version || 'latest' }},enable=${{ github.event_name == 'workflow_dispatch' }}
            type=ref,event=branch,enable=${{ github.event_name != 'workflow_dispatch' }}
            type=ref,event=pr,enable=${{ github.event_name != 'workflow_dispatch' }}
            type=semver,pattern={{version}},enable=${{ github.event_name != 'workflow_dispatch' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name != 'workflow_dispatch' }}
            type=sha,format=long,enable=${{ github.event_name != 'workflow_dispatch' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 
