name: 十分钟Finnhub资讯采集器

on:
  schedule:
    # 每10分钟运行一次
    - cron: '*/10 * * * *'
  
  # 允许手动触发
  workflow_dispatch:
    inputs:
      api_endpoint:
        description: 'API端点URL'
        required: false
        default: 'https://api.easyllms.com/api/info'
        type: string

jobs:
  collect-news:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: yjq001/sex-robot
          path: ./sex-robot
          token: ${{ secrets.PAT_TOKEN }}
          ref: master
          fetch-depth: 1
          persist-credentials: false

      - name: Copy files from private repository
        run: |
          cp -r ./sex-robot/* ./
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r infos/requirements.txt
      
      - name: 运行资讯采集器
        working-directory: ./infos
        run: python finnhub_news_collector.py
        env:
          API_ENDPOINT: ${{ github.event.inputs.api_endpoint || 'https://api.easyllms.com/api/info' }}
      
      - name: 上传日志
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: finnhub-collector-logs
          path: infos/finnhub_collector.log
          retention-days: 1
