name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整的历史记录，包括标签

    - name: Checkout private repository
      uses: actions/checkout@v4
      with:
        repository: yjq001/sex-robot
        path: ./sex-robot
        token: ${{ secrets.PAT_TOKEN }}
        ref: master
        fetch-depth: 1
        persist-credentials: false

    - name: Copy files from private repository
      run: |
        cp -r ./sex-robot/* ./

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel

    - name: Prepare package files
      run: |
        # 创建临时目录用于构建
        mkdir -p ./build_temp
        
        # 复制 mymcp 目录
        cp -r ./mymcp ./build_temp/
        
        # 复制必要的项目文件
        cp pyproject.toml ./build_temp/
        cp setup.py ./build_temp/
        cp README.md ./build_temp/ || echo "README.md not found"
        
        # 切换到临时目录构建
        cd ./build_temp

    - name: Build package
      run: |
        cd ./build_temp
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: ./build_temp/dist
        skip_existing: true
        verbose: true 
