name: Translate Video Metadata

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      
    - name: Checkout private repository
      uses: actions/checkout@v4
      with:
        repository: yjq001/sex-robot
        path: ./sex-robot
        token: ${{ secrets.PAT_TOKEN }}
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary requests python-dotenv configparser
        
    - name: Run translator
      run: |
        # 从私有仓库复制所需文件
        cp ./sex-robot/translate_metadata.py ./translate_metadata.py
        chmod +x translate_metadata.py
        
        # 运行翻译脚本，使用脚本中的默认配置
        python ./translate_metadata.py
        
    - name: Upload logs
      if: always()  # 即使任务失败也上传日志
      uses: actions/upload-artifact@v4
      with:
        name: translation-logs
        path: translate.log 
