name: WSB Video Bot

on:
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      telegram_chat_id:
        description: 'Telegram Chat ID'
        required: false
        default: '-1003444893572'
      version:
        description: 'Docker镜像版本标签'
        required: false
        default: 'latest'
        type: string

jobs:
  run_wsb_video_bot:
    runs-on: ubuntu-22.04
    timeout-minutes: 50
    
    steps:
      - name: Run wsb_video_bot
        run: |
          IMAGE_VERSION="${{ github.event.inputs.version || 'latest' }}"
          docker pull ghcr.io/yjq001/wsb_video_bot:${IMAGE_VERSION}
          
          docker run --rm --network host \
            --name wsb_video_bot \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ github.event.inputs.telegram_chat_id || '-1003444893572' }}" \
            -e TELEGRAM_NOTIFY_ENABLED=true \
            -e TELEGRAM_NOTIFY_URL="https://code.easyllms.com/api/telegram/send" \
            -e TELEGRAM_TIMEOUT_S=10 \
            -e OPENROUTER_API_KEY="${{ secrets.OPENROUTER_API_KEY }}" \
            -e REDDIT_CLIENT_ID="pilB4EG7VFAfZlGj0RmwiA" \
            -e REDDIT_CLIENT_SECRET="AoEQjUzCBf85m1T_1fGDLL2KY3MbMg" \
            -e REDDIT_USER_AGENT="wsb_video_bot/0.1 by u/wsb_video_bot" \
            ghcr.io/yjq001/wsb_video_bot:${IMAGE_VERSION}

